# Generated by Django 4.2.4 on 2023-08-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_tag_opportunities_opportunity_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Research_help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('help_type', models.CharField(choices=[('mentor', 'mentor'), ('student', 'student')], max_length=100)),
                ('interests', models.ManyToManyField(related_name='helpers', to='base.interest')),
            ],
        ),
    ]
