# Generated by Django 4.2.4 on 2023-08-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_research_help_email_alter_opportunity_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('resource_type', models.CharField(choices=[('academics', 'academics'), ('finance', 'finance')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='research_help',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='research_help',
            name='help_type',
            field=models.CharField(choices=[('mentor', 'mentor'), ('student', 'student'), ('study-group', 'study-group'), ('research', 'research'), ('other', 'other')], max_length=100),
        ),
    ]
