# Generated by Django 4.2.4 on 2023-08-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_college_alter_research_help_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='college',
            new_name='college_help',
        ),
    ]
