# Generated by Django 4.2.4 on 2023-08-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_college_college_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='college_help',
            name='topic',
            field=models.CharField(choices=[('School_Before_College', 'School_Before_College'), ('Searching_for_Colleges', 'Searching_for_Colleges'), ('Exam_Prep', 'College_Applications'), ('Research', 'Research'), ('Mentors', 'Mentors'), ('Extracurriculars', 'Extracurriculars'), ('Additional', 'Additional'), ('Navigating_Scholarships', 'Navigating_Scholarships'), ('Financial_Aid', 'Financial_Aid'), ('Sponsors', 'Sponsors'), ('Financial_Literacy_Courses', 'Financial_Literacy_Courses'), ('Additional_resources', 'Additional_resources')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
