# Generated by Django 4.2.4 on 2023-08-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='opportunities',
            field=models.ManyToManyField(blank=True, to='base.opportunity'),
        ),
    ]
