# Generated by Django 4.2.4 on 2023-08-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_interest_research_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='research_help',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='research_help',
            name='help_type',
            field=models.CharField(choices=[('mentor', 'mentor'), ('student', 'student'), ('studygroup', 'studygroup')], max_length=100),
        ),
    ]
